### ISSUE TITLE
[Bug] Volumetric interface

### ISSUE THREAD

**Issue by KartAlexPet** [GTModpackTeam/gregtech-expert-2#109]
### Pack Version

v.1.2.5

### SinglePlay or Server?

SP

### Your Expectation

Wanted to insert pattern expansion card into volumetric interface

### The Reality

Pattern expansion card can't be inserted into volumetric interface

**Comment by tier940** [comment]
The bug you reported is not a modpack bug, Volumetric just can't handle the AE2 Fork version.
Please ask on Discord for another similar bak to confirm.
https://discord.gg/xBwHpZyZdW
