### ISSUE TITLE
[Other] Configure auto deploy to curseforge.

### ISSUE THREAD

**Issue by tier940** [GTModpackTeam/gregtech-expert-2#20]
### Say

APIの設定はOK。チェンジログも載せたいが、最悪ここのレポへのリンクだけでもいい。
また現状だとbetaのciと被りそうなので、確認すること。

**Comment by eighty88** [comment]
CHANGELOG.mdを用意しておけるならそれを載せれるけども

**Comment by eighty88** [comment]
もしくはURL
[https://github.com/GTModpackTeam/gregtech-expert-2/compare/beta-1707400647...beta-1717631276](https://github.com/GTModpackTeam/gregtech-expert-2/compare/beta-1707400647...beta-1717631276)

のように比較が可能なのでこれをChangelog扱いできるかも

**Comment by tier940** [comment]
> CHANGELOG.mdを用意しておけるならそれを載せれるけども

その方式でOK。

**Comment by tier940** [comment]
cfの自動pushを対応してないので再オープン

**Comment by tier940** [comment]
バージョンが最新になってしまう

**Comment by eighty88** [comment]
うーん

やっぱりCurseForge API自体がファイル(jar)のアップロードにしか対応してないのかな?

**Comment by eighty88** [comment]
対応してるっぽいんだけどもな

**Comment by tier940** [comment]
@eighty88 
UPはできてるけどMCVerが1.18.1になる。

**Comment by eighty88** [comment]
https://github.com/henkelmax/upload-curseforge-modpack-action
