### ISSUE TITLE
[Bug]Bending machines overlay incorrectly

### ISSUE THREAD

**Issue by LixFen** [GTModpackTeam/gregtech-expert-2#205]
### Pack Version

v1.10.0-release

### SinglePlay or Server?

SP

### Your Expectation

Try to use bending machine to make plate,Texture display should be normal,but it didn't.
It works good on other pack
Strangely，if you use texture pack ，it will be no problem

### The Reality

![image](https://user-images.githubusercontent.com/89679707/176925529-c3c030cc-c7c7-46d3-8116-32f7f7943cc2.png)
![image](https://user-images.githubusercontent.com/89679707/176926401-f2afb9d0-55b8-41e8-bdab-3345adea70b5.png)
It occurs on any bending machine

**Comment by LixFen** [comment]
> 您能给我们发送您的最新.log我们这边找不到任何问题吗？
sure，https://drive.google.com/file/d/1Oa0bxkuBpEctvzxYtQe5MZ5WV5YLwtNV/view?usp=sharing

**Comment by Quarri6343** [comment]
我们发现你的log确实在载图的时候有吐错误
但GTCEu的程式原来就不会载入不存在的texture，可能是其他模组在作怪
然而我们只会修GTCEu还有CT的问题，所以无法解决你的问题
你可以试试重装整合包

**Comment by LixFen** [comment]
?这确定不是整合包问题？
重新安装后依然存在此问题
尝试使用cf上最新文件安装后依然存在此问题
至少在我的设备上有这个问题

**Comment by LixFen** [comment]
在resource文件夹下添加材质后修复了这个问题，但是依然没办法判断什么原因导致这个问题。
我确定每一个下载此包的人都有这个问题，我在另一台设备上做了测试，同样它发生了
