### ISSUE TITLE
Advanced Chemical Plant can't parallel recipe

### ISSUE THREAD

**Issue by Basicula** [GTModpackTeam/GregTech-Expert-2#376]
### Pack Version

v2.6.7

### SinglePlay or Server?

Single Player

### Your Expectation

All recipes in **Advanced Chemical Plant** can be run in parallel.

### The Reality

I noticed that recipe for **Impure Enriched Naquadah Solution** can't be run parallel in **Advanced Chemical Plant**.
![image](https://github.com/GTModpackTeam/GregTech-Expert-2/assets/32364935/d48ac0d1-091b-4674-bcd0-ff6179462cb5)

My setup for **Advanced Chemical Plant** is EV Quadruple Input Hatch, EV Input Bus, EV Quadruple Output Hatch, EV Output Bus, Master Parallel Control Hatch. So based on this recipe and this setup 16 recipes should be run in parallel.

All other(probably not all but I have issue only with it) recipes can be run parallel on this setup. Maybe I missed something, will be much appreciate for explanation of such behavior. If you need any extra information let me know.

**Comment by MrKono** [comment]
Did you use **UV Energy Hatch** and **Super Voltage Control Unit**?
Impure Enriched Naquadah Solution recipe required **LuV**, so if you want to run that recipe in parallel, you must be able to run it **at least** ZPM or higher..

**Comment by Basicula** [comment]
> Did you use **ZPM Energy Hatch** and **Ultimate Voltage Control Unit** or higher Tier? Impure Enriched Naquadah Solution recipe required **LuV**, so if you want to run that recipe in parallel, you must be able to run it **at least** ZPM or higher..

So paralleling is done only for recipes lower than energy hatch installed? Was it pointed somewhere?

**Comment by MrKono** [comment]
Parallel Logic is the same as Proccesing Array. However, for those with an integrated Voltage Control Unit, the voltage of the Voltage Control Unit is the maximum voltage that can be run.
For example, 16 Parallel EV recipes require LuV. 16 Parallel on a machine with a built-in Voltage Control Unit requires a Master Voltage Control Unit or higher Voltage Control Unit.

**Comment by Basicula** [comment]
Ok, thanks for explanation.
