### ISSUE TITLE
half-block step-assist is broken

### ISSUE THREAD

**Issue by tier940** [GTModpackTeam/gregtech-expert-2#386]
### Pack Version

v2.6.9

### SinglePlay or Server?

Other

### Your Expectation

ジャンプせずにハーフブロックなどを乗り越えられる。

### The Reality

ハーフブロックやベッドなど、ブロックの判定が壊れている。
原因はRoughlyEnoughIDsをv2.0.8にアップグレードしたのが起因。

**Comment by MrKono** [comment]
v2.7.0-alphaでも同様のバグ確認
