### ISSUE TITLE
No boot server

### ISSUE THREAD

**Issue by tier940** [GTModpackTeam/gregtech-expert-2#396]
### Pack Version

2.7.4

### Error Log

https://mclo.gs/yN9Nowy

### SinglePlay or Server?

Multi Player

### Your Expectation

EnderStorage (Ender Storage continuation) crashes when trying to start the server.

### The Reality

The event has already been sent to the development Discord. Awaiting response.

**Comment by TigerWalts** [comment]
This bug was introduced in EnderStorage Continuation 2.6.1

- https://github.com/igentuman/EnderStorage-continuation/issues/14
