### ISSUE TITLE
GT Crafting Station delete items

### ISSUE THREAD

**Issue by niedle2914** [GTModpackTeam/gregtech-expert-2#42]
### Pack Version

v0.9.4

### SinglePlay or Server?

SP

### Type of Server

Single Player

### Your Expectation

Mod "GregTech" で追加される "Crafting Station"のGUIを開いた状態で "Inventory Sorter" の "Sort Inventory" に設定されているキーを入力し、内部インベントリの整頓をおこなう。

### The Reality

"Crafting Station" の内部インベントリにあるアイテムがクラフティンググリッドに移動し、消去されてしまう。
[P.S.]私は日本人です。本パックをプレイ中にこの現象を発見したので報告させていただきます。またこちらは日本語での投稿でも問題ないでしょうか。

**Comment by tier940** [comment]
@niedle2914 
こちらのバグはGTCEu本体側です。なのでModPackとしてはクローズさせていただきます。
※どこかにそのやり取りがあった気がしますが、すいません忘れました...

**Comment by tier940** [comment]
@niedle2914 
コチラにいました。
https://github.com/GregTechCEu/GregTech/pull/502

**Comment by niedle2914** [comment]
ご返答ありがとうございます。Mod本体側の問題ということで把握いたしました。
