### ISSUE TITLE
GT's Solar Panel

### ISSUE THREAD

**Issue by MrKono** [GTModpackTeam/gregtech-expert-2#44]
### Say

Pack Version
v0.9.5

SinglePlay or Server?
SP

Type of Server
Single Player

Your Expectation
Solar Panels are noted "You can't make electricity by creating it XD" in the Tooltip, but it can produce electricity.

The Reality
Put on the top of machine -> Can generate electricity.
Put on the top of Battery Buffer -> Cannot generate electricity.
Put on the Machine Hulls -> Can generate electricity.
Put on the Transformer -> Can generate electricity.

**Comment by tier940** [comment]
@MrKono 
※日本人と分かっているので日本語で返しますね。
Battery Bufferしか試してなかったですが、そのほか行けちゃうのですね...情報ありがとうございます。
