### ISSUE TITLE
[Bug...?] 3D Builder in JEI

### ISSUE THREAD

**Issue by MrKono** [GTModpackTeam/gregtech-expert-2#50]
### Pack Version

v0.12.0

### SinglePlay or Server?

SP

### Type of Server

Single Player

### Your Expectation

バグかどうかわかりませんが一応...
inputが多すぎてはみ出しています。
![2022-02-07_18 50 02](https://user-images.githubusercontent.com/90126004/152766325-fa1b5f82-6bbe-4456-889b-aaebbd6f0749.png)

### The Reality

見辛くて申し訳ありません。
フルスクリーン&GUI最小です。

**Comment by tier940** [comment]
AssemblyLineに切り替えたので大丈夫です。
