### ISSUE TITLE
[Request] Add some sort of Backpacks, to Fight Inventory space Problems!

### ISSUE THREAD

**Issue by bioastroiner** [GTModpackTeam/gregtech-expert-2#52]
### Pack Version

0.12

### Your Proposal

There is wide range of Backpack mods idk witch one fits the best
1) [Improved Backpacks](https://www.curseforge.com/minecraft/mc-mods/improvedbackpacks) 
Placable has a hotkey and is wearble the con is, it's no longer being maintained
2) Iron Backpacks, tiered and has a hotkey much more spaces than last one

### Your Goal

See there is only 2 method of extending players inventory currently (Ender pouch and AE2 Handheld thingy) witch both are gated way far in the tech tree,

### Your Vision

Considering How much gregtech occupies the spaces of your inventory with all those tools an' stuffs, you need some sort of Backpack, witch this pack really needs

**Comment by tier940** [comment]
@bioastroiner 
I need /dank/null. Is there any reason why that is not good?
※You can also use it as a backpack, just in case.
