### ISSUE TITLE
[Bug] red alloy dust

### ISSUE THREAD

**Issue by Valorzsan** [GTModpackTeam/gregtech-expert-2#55]
### Pack Version

v0.13.1

### SinglePlay or Server?

SP

### Your Expectation

early game: start crafting steam machines

### The Reality

no way to craft red alloy dust without machines

**Comment by tier940** [comment]
It will be supported in the next version.
![image](https://user-images.githubusercontent.com/11691836/153571228-adb0a85d-36f3-4ab0-bfc9-dbf229b401a9.png)
