### ISSUE TITLE
[Request]Compact Drawers compress GT dusts

### ISSUE THREAD

**Issue by niedle2914** [GTModpackTeam/gregtech-expert-2#57]
### Pack Version

v0.13.1

### Your Proposal

各種 Compact Drawers に Gregtech の Dust / Small ~" / Tiny ~" を変換,収納できる機能を実装する。

### Your Goal

例えば Conpact Drawers に Dark Ashes を収納すると Dark Ashes / Small Pile of ~" / Tiny Pile of ~" として取り出せるようにすることは可能でしょうか。

### Your Vision

バニラの鉄ブロックなどは変換が可能ですが想定外の挙動であれば修正をお願いします。

**Comment by tier940** [comment]
申し訳ございませんが、コチラは対応は致しません。

> バニラの鉄ブロックなどは変換が可能ですが想定外の挙動であれば修正をお願いします。
実はコレ、前バージョンにもある隠し機能として実装してるだけです。
