### ISSUE TITLE
[Request] Greenhouse cannot be configured

### ISSUE THREAD

**Issue by niedle2914** [GTModpackTeam/gregtech-expert-2#66]
### Pack Version

v0.13.4

### SinglePlay or Server?

SP

### Type of Server

Single Player

### Your Expectation

Greenhouse に骨粉と Programmed Circuit を入れて倍化レシピを稼働させる。

### The Reality

Programmed Circuit の設定値に関わらず骨粉の有無でレシピが決定され、設定を変更するにはマシンを再設置する必要がある。

**Comment by tier940** [comment]
その時のTwitchを見ていましたが、並行稼働はサポートしていません。
またCircuitを二個置いてましたが、あれでは作動中が優先されます。

**Comment by niedle2914** [comment]
確認ありがとうございます。
あの後こちらでも調査しましたが、 Programmed Circuit の値を [1] 及び [2] 以外の値に設定しても同様の結果となりました。

**Comment by tier940** [comment]
最新バージョンで対応しました。
インプットとアウトプットの値をミスってたぽいです。
https://github.com/GTModpackTeam/gregtech-expert-2/blob/main/overrides/scripts/_Init.zs#L67-L67
