### ISSUE TITLE
[QUESTION/BUG?]

### ISSUE THREAD

**Issue by MrKono** [GTModpackTeam/gregtech-expert-2#79]
### Pack Version

v1.1.2

### SinglePlay or Server?

SP

### Type of Server

Single Player

### Your Expectation

1. Discordのリンク切れ？
2. v1.1.2でクラッシュ

### The Reality

2.について
クラレポ (抜粋)
java.lang.IllegalArgumentException: material is not registered
crafttweaker.log (抜粋)
[PREINITIALIZATION][CLIENT][ERROR] [gregtech]: Error executing {[0:gregtech]: materials.zs}: Tried to reassign id 32100 to electrical_steel (electrical_steel), but it is already assigned to electrical_steel (null)!
java.lang.IllegalArgumentException: Tried to reassign id 32100 to electrical_steel (electrical_steel), but it is already assigned to electrical_steel (null)!

material.zsを抜くと起動確認
ただし32000_Greenhouse.zs及び32001_VoidOreMiner.zsにおいても同様のIDエラーが起きている模様

**Comment by tier940** [comment]
@MrKono 
気が付いていたので次のバージョンで更新します。
> Discordのリンク切れ？

現在確認中です
> v1.1.2でクラッシュ

**Comment by MrKono** [comment]
2については私の環境(といってもただアプデしただけですが)の問題もあるかもしれませんが一応報告させていただきました。

**Comment by tier940** [comment]
こちらは起きませんのでおま環ってやつですね...
> 2については私の環境(といってもただアプデしただけですが)の問題もあるかもしれませんが一応報告させていただきました。

**Comment by Quarri6343** [comment]
2についてこちらの環境でも起きていません

**Comment by tier940** [comment]
@MrKono 
リンク切れしていたので今回はたどり着けずもうしわけなかったですが、疑問形のissueはまずDiscordでお願いします。
https://discord.gg/xBwHpZyZdW

**Comment by MrKono** [comment]
分かりました。ありがとうございます。
