### ISSUE TITLE
Remove additional recipes from Chisel.

### ISSUE THREAD

**Issue by tier940** [GTModpackTeam/gregtech-expert-2#8]
There is no on/off in Chisel's cfg.
It also has a high priority and cannot be deleted added.

**Comment by eighty88** [comment]
https://github.com/GTModpackTeam/Chisel/releases/tag/1.12.2-GT-01

**Comment by eighty88** [comment]
https://github.com/GTModpackTeam/Chisel/releases/download/1.12.2-GT-01/Chisel-MC1.12.2-GT.jar
